version: '3.8'
services:

  middleware:
    image: devaten/devaten-middleware-prometheus:latest
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file: middleware.env
    container_name: devaten-middleware-prometheus
    depends_on: 
      - prometheus
    restart: always
    ports:
      - 8999:8999
      - 9091:9091
    networks:
      - middleware

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 0.0.0.0:9090:9090 
    environment:
      - AUTH_USER=EnterUsername
      - AUTH_PASS=EnterPassword  
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml 
      - ./prometheus/web.yml:/etc/prometheus/web.yml  
      - ./prometheus/config/:/etc/prometheus/
      - ./prometheus/data/:/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web.yml'
     
    networks:
      - middleware

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 0.0.0.0:3000:3000 
    environment:
     - GF_SECURITY_ADMIN_USER=EntetUsername
     - GF_SECURITY_ADMIN_PASSWORD=EnterPassword
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_AUTH_BASIC_ENABLED=false
     - GF_SECURITY_API_ENABLED=true
     - GF_SECURITY_DISABLE_GRAFANA_SIGNOUT_REDIRECT=true
     - GF_SECURITY_ENFORCE_SSL=false
     - GF_SECURITY_ALLOW_EMBEDDING=true
     - GF_SECURITY_COOKIE_SAMESITE=lax
    depends_on:
      - prometheus 
    volumes:
      - './grafana-data/datasources:/etc/grafana/provisioning/datasources'
      - './grafana-data:/var/lib/grafana:cached'
      - './grafana-data/grafana-plugins:/etc/grafana/plugins'
      - './grafana-data/grafana-dashboards:/etc/grafana/dashboards'

    networks:
      - middleware
   
networks:
  middleware:
    name: middleware

volumes:
  prometheus_data: {}
  grafana-data: {}