{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DBINSTANCE_ID",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DBINSTANCE_ID_NUM_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DBINSTANCE_SIZEMB",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DBINSTANCE_SIZEMB_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DBINSTANCE_DEADLOCKS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "targets": [
    { "expr": "DBINSTANCE_DEADLOCKS_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DBINSTANCE_TEMP_FILES",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DBINSTANCE_TEMP_FILES_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_APPLICATION_ID_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "MSSQL_Instance Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  { "title": "MSSQL_Run_Situation_Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "RUN_WAIT_DURATION_MS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "RUN_WAIT_DURATION_MS_MSSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RUN_AVG_WORKER_TIME",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "RUN_AVG_WORKER_TIME_MSSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RUN_AVG_ELAPSED_TIME",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "RUN_AVG_ELAPSED_TIME_MSSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RUN_NUM_EXECUTIONS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "targets": [
    { "expr": "RUN_NUM_EXECUTIONS_MSSQL_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RUN_SQLPROCESSUTILIZATION",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "RUN_SQLPROCESSUTILIZATION_MSSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "MostExecuted_Statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "TABLEANALYSISDATA_NUM_EXECUTIONS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_NUM_EXECUTIONS_MSSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TABLEANALYSISDATA_SPL_PER_SEC",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_SPL_PER_SEC_MSSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_AVG_ELAPSED_TIME_MSSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STOP_NUM_EXECUTIONS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "STOP_NUM_EXECUTIONS_MSSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOSTEXECUTE_NUM_EXECUTIONS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MOSTEXECUTE_NUM_EXECUTIONS_MSSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOSTEXECUTE_LAST_WORKER_TIME",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_LAST_WORKER_TIME_MSSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}