{
 "title": "MySQL Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "MySQL instance info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "STATEMENTS",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DBINSTANCE_STATEMENTS_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DATABASE_SIZE_IN_MB",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_DATABASE_SIZE_IN_MB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CURRENT CONNECTIONS ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_CURRENT_CONNECTIONS_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL_MEMORY_ALLOCATED",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_TOTAL_MEMORY_ALLOCATED_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FILE IO LATENCY",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_FILE_IO_LATENCY_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TABLE_SCANS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DBINSTANCE_TABLE_SCANS_GAUGE", "legendFormat": "__auto" }
   ]
  },
  { "title": "MySQL runsituation data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "BUFFER_POOL_READS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "RUN_BUFFER_POOL_READS_MYSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ROW_LOCK_CURRENT_WAITS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 9 },
   "targets": [
    {
     "expr": "RUN_LOCK_ROW_LOCK_CURRENT_WAITS_MYSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ROWS_SCANNED",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 9 },
   "targets": [
    { "expr": "RUN_ROWS_SCANNED_MYSQL_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SUM_ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 9 },
   "targets": [
    { "expr": "RUN_SUM_ERRORS_MYSQL_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU_USER_TIME_SPENT",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "RUN_TOTAL_CPU_USER_TIME_SPENT_MYSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EXECUTION COUNT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "targets": [
    { "expr": "RUN_COUNT_STAR_MYSQL_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "OS_DATA_READS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "RUN_OS_DATA_READS_MYSQL_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "LOCK_CURRENT_WAITS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 14 },
   "targets": [
    {
     "expr": "RUN_LOCK_ROW_LOCK_CURRENT_WAITS_MYSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LOCK_DEADLOCKS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 14 },
   "targets": [
    { "expr": "RUN_LOCK_DEADLOCKS_MYSQL_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TOTAL_CPU_SYSTEM_TIME_SPENT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "RUN_TOTAL_CPU_SYSTEM_TIME_SPENT_MYSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOST EXECUTED  TIME AVGMS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_EXECTIMEAVGMS_MYSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TOP 20 SQL Statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "MOST EXECUTED_SQLS ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_EXECCOUNT_MYSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOST EXECUTED SQLS",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_EXECCOUNT_MYSQL_GAUGE{appClassname!=\"appClassname\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "EXECTIMETOTAL SQL",
   "type": "table",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "WORSTEXECUTE_EXECTIMETOTAL_MYSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TABLEANALYSISDATA EXECCOUNT",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_EXECCOUNT_MYSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EXECTIMETOTAL",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 8, "y": 44 },
   "targets": [
    {
     "expr": "WORSTEXECUTE_EXECTIMETOTAL_MYSQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TABLEANALYSISDATA_EXECCOUNT",
   "type": "table",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_EXECCOUNT_MYSQL_GAUGE",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}