{
 "title": "Mysql Database tmplate",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "appIpAddress", "label": "appIpAddress", "query": { "query": "" } },
   {
    "name": "idNum",
    "label": "Run id",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,idNum)"
    }
   },
   {
    "name": "databaseName",
    "label": "Application database",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,databaseName)"
    }
   },
   {
    "name": "usecase",
    "label": "use case",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,usecase)"
    }
   },
   {
    "name": "database",
    "label": "database",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,database)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{release=\"$release\", instance=\"$instance\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DBINSTANCE_DATABASE_SIZE_MB{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"})"
    }
   ]
  },
  {
   "title": "Data size ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DBINSTANCE_DATA_SIZE_MB{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"})"
    }
   ]
  },
  {
   "title": "Index size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DBINSTANCE_INDEX_SIZE_MB{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"})"
    }
   ]
  },
  {
   "title": "avg memory allocated",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DBINSTANCE_CURRENT_AVG_ALLOC{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"})"
    }
   ]
  },
  {
   "title": "Memory allocated",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DBINSTANCE_CURRENT_ALLOCATED{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"})",
     "legendFormat": "{{label_name}} = Connections in use"
    }
   ]
  },
  {
   "title": "Average CPU process Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_virtual_memory_max_bytes[5m]))",
     "legendFormat": "Virtual Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes[5m]))",
     "legendFormat": "Resident Mem"
    }
   ]
  },
  {
   "title": "Average CPU process Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total[5m]))",
     "legendFormat": "CPU process"
    },
    {
     "expr": "avg(rate(process_virtual_memory_max_bytes[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes[5m]))",
     "legendFormat": "Resident Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "Open FD" }
   ]
  },
  {
   "title": "death locks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "RUN_LOCK_DEADLOCKS_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}"
    }
   ]
  },
  {
   "title": "BUFFER STATS ALLOCATED",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_BUFFER_STATS_ALLOCATED{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}"
    }
   ]
  },
  {
   "title": "BUFFER_STATS DATA",
   "type": "stat",
   "description": "The total number of data bytes allocated for the schema.\n\n",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_BUFFER_STATS_DATA{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}"
    }
   ]
  },
  {
   "title": "FULL SCANS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_FULL_SCANS{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}\r\n"
    }
   ]
  },
  {
   "title": "rows_sent",
   "type": "stat",
   "description": "The total number of rows returned by statements for the host.\n\n",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_ROWS_SENT{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}"
    }
   ]
  },
  {
   "title": "ROWS EXAMINED",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_ROWS_EXAMINED{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}"
    }
   ]
  },
  {
   "title": "ROWS AFFECTED",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_ROWS_AFFECTED{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}"
    }
   ]
  },
  {
   "title": "total latency",
   "type": "stat",
   "description": "The total wait time of timed statements for the host.",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_TOTAL_LATENCY{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}"
    }
   ]
  },
  {
   "title": "LOCK LATENCY",
   "type": "stat",
   "description": "The total time waiting for locks by timed statements for the host.",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_LOCK_LATENCY{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}"
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "RUN_THREADS_CONNECTED_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "Act count"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "RUN_TRX_ACTIVE_TRANSACTIONS_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "RUN_TRX_COMMITS_INSERT_UPDATE_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "RUN_TRX_ROLLBACKS_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "RUN_COUNT_STAR_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{datname}} commits"
    }
   ]
  },
  {
   "title": " Database CPU Usage",
   "type": "timeseries",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "RUN_TOTAL_CPU_SYSTEM_TIME_SPENT_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "System CPU time"
    },
    {
     "expr": "RUN_TOTAL_CPU_USER_TIME_SPENT_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "User CPU time"
    }
   ]
  },
  {
   "title": "SQL throughput",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "RUN_DML_INSERTS_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "Inserts"
    },
    {
     "expr": "RUN_DML_UPDATES_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "Updates"
    },
    {
     "expr": "RUN_DML_DELETES_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "Deletes"
    },
    {
     "expr": "RUN_DML_READS_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Lock wait time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "RUN_SUM_LOCK_TIME_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "Lock time"
    }
   ]
  },
  {
   "title": "Session info",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "WHOISACTIVE_ROWS_EXAMINED", "legendFormat": "Rows examined" },
    { "expr": "WHOISACTIVE_rows_affected", "legendFormat": "rows affected" },
    {
     "expr": "WHOISACTIVE_waiting_trx_rows_locked",
     "legendFormat": "waiting trx rows locked"
    },
    {
     "expr": "WHOISACTIVE_blocking_trx_rows_locked",
     "legendFormat": "blocking trx rows locked"
    },
    { "expr": "WHOISACTIVE_waiting_trx_age", "legendFormat": "waiting trx age" }
   ]
  },
  {
   "title": "Return data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "RUN_SUM_ROWS_AFFECTED_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}\r\n",
     "legendFormat": "{{label_name}} = Return data"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "RUN_CONFLICTS_POSTGRESQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"} ",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "RUN_DEADLOCKS_POSTGRESQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{instance=\"$instance\"}[5m])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Temp data (Bytes)",
   "type": "timeseries",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "RUN_LOG_WRITE_REQUESTS_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{label_name}} = Temp_bytes"
    },
    {
     "expr": "RUN_LOG_WAITS_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{label_name}} = Temp files"
    },
    {
     "expr": "RUN_LOG_FLUSH_TOTAL_TIME_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{label_name}} = Temp files"
    },
    {
     "expr": "RUN_OS_LOG_PENDING_FSYNCS_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{label_name}} = Temp files"
    },
    {
     "expr": "RUN_OS_LOG_BYTES_WRITTEN_MYSQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{label_name}} = Temp files"
    }
   ]
  },
  {
   "title": "Table info used in previous run",
   "type": "table",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_TABLE_ROWS_MYSQL",
     "legendFormat": "__auto"
    },
    {
     "expr": "TABLEANALYSISDATA_DATA_LENGTH_MYSQL",
     "legendFormat": "__auto"
    },
    {
     "expr": "TABLEANALYSISDATA_INDEX_LENGTH_MYSQL",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TOP 20 Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 }, "repeat": "DS_PROMETHEUS" },
  {
   "title": "TOP 20 Most executed SQL with application trace",
   "type": "table",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "MOSTEXECUTE_EXECCOUNT_MYSQL{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} = exec count"
    },
    {
     "expr": "MOSTEXECUTE_EXECTIMETOTAL_MYSQL{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}}=Exec time"
    },
    {
     "expr": "MOSTEXECUTE_TEMPBLKSREAD_POSTGRESQL{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} = TempBLK_read"
    },
    {
     "expr": "MOSTEXECUTE_EXECTIMETOTAL_MYSQL{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} = Exec time total"
    }
   ]
  },
  {
   "title": "TOP 20 Long running  SQLs with application trace",
   "type": "table",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "WORSTEXECUTE_EXECCOUNT_MYSQL{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} = exec count"
    },
    {
     "expr": "WORSTEXECUTE_EXECTIMETOTAL_MYSQL{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}}= per calls"
    },
    {
     "expr": "WORSTEXECUTE_MAXTIMERWAIT_MYSQL{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} = Rows"
    },
    {
     "expr": "WORSTEXECUTE_SUMSELECTSCAN_MYSQL{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} = Hit percent"
    },
    {
     "expr": "WORSTEXECUTE_SUMLOCKTIME_MYSQL{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} = mean time"
    }
   ]
  },
  { "title": "TABLE info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Checkpoint Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{instance=\"$instance\"}[5m])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{instance=\"$instance\"}[5m])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  }
 ]
}