{
 "title": "New-Postgresql-Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "PostgreSQL_Instance_Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DBINSTANCE_APPLICATION_ID",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_APPLICATION_ID_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DBINSTANCE_CURRENT_CONNECTIONS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "DBINSTANCE_CURRENT_CONNECTIONS_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DBINSTANCE_DATABASE_SIZE_IN_MB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "DBINSTANCE_DATABASE_SIZE_IN_MB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DBINSTANCE_STATEMENTS",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DBINSTANCE_STATEMENTS_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DBINSTANCE_STATEMENT_LATENCY_IN_S",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_STATEMENT_LATENCY_IN_S_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PostgreSQL_Runsituation_Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "RUN_CALLS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "RUN_CALLS_POSTGRESQL_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RUN_ID_NUM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 8 },
   "targets": [
    { "expr": "RUN_ID_NUM_POSTGRESQL_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RUN_TOTAL_TIME",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "RUN_TOTAL_TIME_POSTGRESQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RUN_WAITING_XACT_DURATION",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "RUN_WAITING_XACT_DURATION_POSTGRESQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Top 20 SQL Statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "MOSTEXECUTE_CALLS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_CALLS_POSTGRESQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOSTEXECUTE_ROWSPER",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MOSTEXECUTE_ROWSPER_POSTGRESQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TABLEANALYSISDATA_CALLS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_CALLS_POSTGRESQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOSTEXECUTE_TIMESPEND",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 17 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_TIMESPEND_POSTGRESQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TABLEANALYSISDATA_SPL_PER_SEC",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_SPL_PER_SEC_POSTGRESQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TABLEANALYSISDATA_SEQ_SCAN",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 24 },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_SEQ_SCAN_POSTGRESQL_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}