{
 "title": "New_MariaDB_Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "MariaDB Instance Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DBINSTANCE_CURRENT_CONNECTIONS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_CURRENT_CONNECTIONS_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DBINSTANCE_DATABASE_SIZE_IN_MB",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_DATABASE_SIZE_IN_MB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DBINSTANCE_EXECUTIONS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "targets": [
    { "expr": "DBINSTANCE_EXECUTIONS_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DBINSTANCE_FILE_IO_LATENCY_IN_S",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_FILE_IO_LATENCY_IN_S_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DBINSTANCE_STATEMENTS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 1 },
   "targets": [
    { "expr": "DBINSTANCE_STATEMENTS_GAUGE", "legendFormat": "__auto" }
   ]
  },
  { "title": "MariaDB RunSituationData", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "RUN_SUM_SORT_ROWS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "RUN_SUM_SORT_ROWS_MARIADB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RUN_COUNT_STAR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "RUN_COUNT_STAR_MARIADB_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RUN_STARTTIMESTMAP",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "RUN_STARTTIMESTMAP_MARIADB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RUN_EXEC_TIME_MAX",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "RUN_EXEC_TIME_MAX_MARIADB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RUN_EXEC_TIME_MAX",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "RUN_EXEC_TIME_MAX_MARIADB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Top 20 SQL Statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "MOSTEXECUTE_EXECTIMETOTAL",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_EXECTIMETOTAL_MARIADB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOSTEXECUTE_ROWSSENTAVG",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 9, "y": 15 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_ROWSSENTAVG_MARIADB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TABLEANALYSISDATA_SPL_PER_SEC",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_SPL_PER_SEC_MARIADB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOSTEXECUTE_ROWSSENTAVG",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_ROWSSENTAVG_MARIADB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TABLEANALYSISDATA_DATA_LENGTH",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_DATA_LENGTH_MARIADB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TABLEANALYSISDATA_TABLE_ROWS",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_TABLE_ROWS_MARIADB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOSTEXECUTE_SUMSELECTFULLJOIN",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_SUMSELECTFULLJOIN_MARIADB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}