{
 "title": "New_MongoDB_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "MongoDB_Instance_Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DBINSTANCE_APPLICATION_ID",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_APPLICATION_ID_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DBINSTANCE_DATA_SOURCE_ID_GAUGE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_DATA_SOURCE_ID_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DBINSTANCE_SIZEMB_GAUGE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DBINSTANCE_SIZEMB_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DBINSTANCE_DB_SIZE_GB_GAUGE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DBINSTANCE_DB_SIZE_GB_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DBINSTANCE_EXECUTIONS_GAUGE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DBINSTANCE_EXECUTIONS_GAUGE", "legendFormat": "__auto" }
   ]
  },
  { "title": "MongoDB_RunSituation ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "RUN_APPLICATIONID_MONGODB_GAUGE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "RUN_APPLICATIONID_MONGODB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RUN_CONNECTIONS__AVAILABLE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "RUN_CONNECTIONS__AVAILABLE_MONGODB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RUN_GLOBALLOCK__TOTALTIME_MONGODB_GAUGE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "RUN_GLOBALLOCK__TOTALTIME_MONGODB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RUN_GLOBALLOCK__TOTALTIME_MONGODB_GAUGE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "RUN_OPCOUNTERS__QUERY_MONGODB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RUN_OPCOUNTERS__QUERY_MONGODB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "RUN_OPCOUNTERS__QUERY_MONGODB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "MongoDB Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "MOSTEXECUTE_ADVANCED_MONGODB_GAUGE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_ADVANCED_MONGODB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOSTEXECUTE_DOCSEXAMINED",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 17 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_DOCSEXAMINED_MONGODB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOSTEXECUTE_EXECUTIONTIMEMILLISESTIMATE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_EXECUTIONTIMEMILLISESTIMATE_MONGODB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOSTEXECUTE_KEYSEXAMINED_MONGODB_GAUGE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_KEYSEXAMINED_MONGODB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOSTEXECUTE_MAXRESPONSETIME",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_MAXRESPONSETIME_MONGODB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TABLEANALYSISDATA_AVGOBJSIZE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_AVGOBJSIZE_MONGODB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TABLEANALYSISDATA_COUNT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 23 },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_COUNT_MONGODB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TABLEANALYSISDATA_SIZE_MONGODB_GAUGE",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_SIZE_MONGODB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TABLEANALYSISDATA_STORAGESIZE",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_STORAGESIZE_MONGODB_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}