{
 "title": "ORACLE TEMPLATE_NEW",
 "description": "This dashboard works with Sap hana",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "database",
    "label": "Database type",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,database)"
    }
   },
   {
    "name": "usecase",
    "label": "use case",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,usecase)"
    }
   },
   {
    "name": "idNum",
    "label": "Run id",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,idNum)"
    }
   },
   {
    "name": "databaseName",
    "label": "Aplication_database",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,databaseName)"
    }
   },
   {
    "name": "starttimestamp",
    "label": "starttimestamp",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,starttimestamp)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database size",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_DB_SIZE_GB{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}"
    }
   ]
  },
  {
   "title": "NUMBER OF SESSIONS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_NUMBEROFSESSIONS{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ACTIVE USER SESSIONS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_ACTIVEUSERSESSIONS{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PERCENT OF MAX SESSIONS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_PERCENTOFMAXSESSIONS{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}"
    }
   ]
  },
  {
   "title": "PERCENT OF MAX OPEN CURSORS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_PERCENTOFMAXOPENCURSORS{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffer hit ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_BUFFERCACHEHITRATIO{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}"
    }
   ]
  },
  {
   "title": "Cursor cache hitratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_CURSORCACHEHITRATIO{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Library cache hitratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_LIBRARYCACHEHITRATIO{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "Open FD" }
   ]
  },
  {
   "title": "Number of executions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "RUN_EXECUTIONS_ORACLE{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "Num executions"
    }
   ]
  },
  {
   "title": "Elapsed time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "RUN_ELAPSED_TIME_ORACLE{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "Num executions"
    }
   ]
  },
  {
   "title": "Runtime MEM ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "RUN_RUNTIME_MEM_ORACLE{database=\"$database\", databaseName=\"$databaseName\", usecase=\"$usecase\", idNum=\"$idNum\"}",
     "legendFormat": "Run time"
    }
   ]
  },
  {
   "title": "Run time MEM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "RUN_RUNTIME_MEM_ORACLE{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} SQL COMPILATIONS SEC"
    }
   ]
  },
  {
   "title": "Sharable MEM ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "RUN_SHARABLE_MEM_ORACLE{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} SQL COMPILATIONS SEC"
    }
   ]
  },
  {
   "title": "who is active",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    { "expr": "WHOISACTIVE_ELAPSED_TIME", "legendFormat": "__auto" },
    { "expr": "WHOISACTIVE_CPU_TIME", "legendFormat": "__auto" },
    { "expr": "WHOISACTIVE_TOTALPHYIO_MB", "legendFormat": "__auto" },
    { "expr": "WHOISACTIVE_SECONDS_IN_WAIT", "legendFormat": "__auto" }
   ]
  },
  { "title": "Session live metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Reads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "RUN_DISK_READS_ORACLE{database=\"$database\", databaseName=\"$databaseName\", usecase=\"$usecase\", idNum=\"$idNum\"}",
     "legendFormat": "Disk reads"
    },
    {
     "expr": "RUN_FETCHES_ORACLE{database=\"$database\", databaseName=\"$databaseName\", usecase=\"$usecase\", idNum=\"$idNum\"} != 0",
     "legendFormat": "Fetches"
    },
    {
     "expr": "RUN_LOADS_ORACLE{database=\"$database\", databaseName=\"$databaseName\", usecase=\"$usecase\", idNum=\"$idNum\"}",
     "legendFormat": "Loads"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "\t\nDisplays the connection status:\n\nRUNNING\nA statement is executing.\n\nIDLE\nNo statements are currently executing on this connection.\n\nQUEUING\nThe connection is currently queued. The status changes to RUNNING when it is dequeued (this depends on the system's resource consumption).\n\nEMPTY\nA historic connection that is removed after 1 hour. The removal time can be configured in indexserver.ini [session] connection_history_lifetime = 60 # minutes.",
   "gridPos": { "h": 9, "w": 6, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "RUN_USERCOMMITS_ORACLE{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "User commits"
    },
    {
     "expr": "RUN_ROLLBACKS_ORACLE{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Session Elapsed time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "avg(WHOISACTIVE_ELAPSED_TIME)", "legendFormat": "Mem usage" }
   ]
  },
  {
   "title": "Session  CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "avg(WHOISACTIVE_CPU_TIME)", "legendFormat": "Total CPU" }
   ]
  },
  {
   "title": "User IO wait time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "RUN_USER_IO_WAIT_TIME_ORACLE{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "User IO wait time"
    }
   ]
  },
  {
   "title": "Application wait time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "RUN_APPLICATION_WAIT_TIME_ORACLE{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "description": "Latest start & stop recording used tables",
   "gridPos": { "h": 14, "w": 8, "x": 15, "y": 45 },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_ROWCOUNTS_ORACLE",
     "legendFormat": "__auto"
    },
    {
     "expr": "TABLEANALYSISDATA_PCT_FREE_ORACLE",
     "legendFormat": "__auto"
    },
    {
     "expr": "TABLEANALYSISDATA_PCT_USED_ORACLE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Physical reads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "RUN_PHYSICAL_READ_BYTES_ORACLE{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}}Logical writes"
    }
   ]
  },
  {
   "title": "Physical read requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "RUN_PHYSICAL_READ_REQUESTS_ORACLE{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} Active plans"
    }
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Physical writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "RUN_PHYSICAL_WRITE_BYTES_ORACLE{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} Reads"
    }
   ]
  },
  {
   "title": "Physical write requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "RUN_PHYSICAL_WRITE_REQUESTS_ORACLE {database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} LOG READ THROUGHPUT MB"
    },
    {
     "expr": "RUN_LOGWRITETHROUGHPUTMB{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} LOG WRITE THROUGHPUT MB"
    }
   ]
  },
  { "title": "TOP 20 SQL details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Top 20 most executed queries",
   "type": "table",
   "description": "Latest start & stop recording queries for selected usecase",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_EXECCOUNT_ORACLE {database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\"} !=0",
     "legendFormat": "__auto"
    },
    {
     "expr": "MOSTEXECUTE_TOTAL_ELAPSED_TIME_ORACLE {database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\"} !=0",
     "legendFormat": "__auto"
    },
    {
     "expr": "MOSTEXECUTE_LAST_LOGICAL_READS_ORACLE {database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\"} !=0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOP 20 most executed queries",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "MOSTEXECUTE_EXECCOUNT_ORACLE{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}!=0",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top 20 long running queries",
   "type": "table",
   "description": "Latest start & stop recording queries for selected use case",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "WORSTEXECUTE_ELAPSED_TIME_ORACLE{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "WORSTEXECUTE_FETCHES_ORACLE{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "WORSTEXECUTE_PHYSICAL_READ_BYTES_ORACLE{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOP 20 slow runnig queries",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "WORSTEXECUTE_ELAPSED_TIME_ORACLE{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{queryid}}"
    }
   ]
  }
 ]
}