{
 "title": "PostgreSQL Database",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
    }
   },
   {
    "name": "release",
    "label": "Release",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
    }
   },
   { "name": "appIpAddress", "label": "appIpAddress", "query": { "query": "" } },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "mode",
    "label": "Lock table",
    "query": {
     "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{release=\"$release\", instance=\"$instance\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DBINSTANCE_DATABASE_SIZE_GAUGE" }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(DBINSTANCE_TUP_UPDATED_GAUGE{datname=~\"$datname\"})"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(DBINSTANCE_TUP_INSERTED_GAUGE{release=\"$release\", datname=~\"$datname\"})"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(DBINSTANCE_TUP_UPDATED_GAUGE{datname=~\"$datname\"})"
    }
   ]
  },
  {
   "title": "Connections in use",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_ACTIVE_CONEECTIONS_GAUGE",
     "legendFormat": "{{label_name}} = Connections in use"
    }
   ]
  },
  {
   "title": "Average CPU process Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_virtual_memory_max_bytes[5m]))",
     "legendFormat": "Virtual Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes[5m]))",
     "legendFormat": "Resident Mem"
    }
   ]
  },
  {
   "title": "Average CPU process Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total[5m]))",
     "legendFormat": "CPU process"
    },
    {
     "expr": "avg(rate(process_virtual_memory_max_bytes[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes[5m]))",
     "legendFormat": "Resident Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "Open FD" }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_EFFECTIVE_CACHE_SIZE_GAUGE"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_EFFECTIVE_CACHE_SIZE_GAUGE"
    }
   ]
  },
  {
   "title": "REPLICATION DELAY ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_REPLICATION_DELAY_IN_SECONDS_GAUGE"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DBINSTANCE_WORK_MEM_GAUGE" }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_WAL_SEGMENT_SIZE_GAUGE"
    }
   ]
  },
  {
   "title": "Num backends",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DBINSTANCE_NUMBACKENDS_GAUGE" }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DBINSTANCE_SEQ_PAGE_COST_GAUGE" }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_MAX_WORKER_PROCESSES_GAUGE"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_MAX_PARALLEL_WORKERS_GAUGE"
    }
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active sessions",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "DBINSTANCE_ACT_COUNT_GAUGE !=0", "legendFormat": "{{datname}}, s: {{state}}" },
    {
     "expr": "DBINSTANCE_MAXCONNECTION_IN_USE_PERCENT_GAUGE",
     "legendFormat": "{{label_name}} = Connections in use"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(RUN_TOTAL_COMMITS_POSTGRESQL_GAUGE[15s])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(RUN_TOTAL_ROLLBACKS_POSTGRESQL_GAUGE[15s])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "SQL throughput",
   "type": "graph",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "RUN_TUP_FETCHED_POSTGRESQL_GAUGE != 0",
     "legendFormat": "{{datname}} = Select"
    },
    {
     "expr": "RUN_TUP_INSERTED_POSTGRESQL_GAUGE",
     "legendFormat": "{{label_name}}= Insert"
    },
    {
     "expr": "RUN_TUP_UPDATED_POSTGRESQL_GAUGE",
     "legendFormat": "{{label_name}} = Update"
    },
    {
     "expr": "RUN_TUP_DELETED_POSTGRESQL_GAUGE",
     "legendFormat": "{{label_name}}= delete"
    }
   ]
  },
  {
   "title": "Waiting & locking time",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "RUN_LOCKING_QUERY_DURATION_POSTGRESQL_GAUGE",
     "legendFormat": "{{label_name}} = Locking_QUERY_duration"
    },
    {
     "expr": "RUN_LOCKING_XACT_DURATION_POSTGRESQL_GAUGE",
     "legendFormat": "{{label_name}} = Locking_XACT_duration"
    },
    {
     "expr": "RUN_WAITING_QUERY_DURATION_POSTGRESQL_GAUGE",
     "legendFormat": "{{label_name}}= Waiting _QUERY_duration"
    },
    {
     "expr": "RUN_WAITING_XACT_DURATION_POSTGRESQL_GAUGE",
     "legendFormat": "{{label_name}} = Waiting_XACT_duration"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "RUN_TUP_RETURNED_POSTGRESQL_GAUGE != 0",
     "legendFormat": "{{label_name}} = Return data"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 14, "w": 11, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(RUN_CONFLICTS_POSTGRESQL_GAUGE[15s])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(RUN_DEADLOCKS_POSTGRESQL_GAUGE[15s])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "DBINSTANCE_BLKS_HIT_GAUGE / (DBINSTANCE_BLKS_READ_GAUGE + DBINSTANCE_BLKS_HIT_GAUGE)",
     "legendFormat": "{{label_name}}= "
    }
   ]
  },
  {
   "title": "Temp data (Bytes)",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(DBINSTANCE_TEMP_BYTES_GAUGE[5m])",
     "legendFormat": "{{label_name}} = Temp_bytes"
    },
    { "expr": "DBINSTANCE_TEMP_FILES_GAUGE", "legendFormat": "{{label_name}} = Temp files" }
   ]
  },
  {
   "title": "Average Database CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(RUN_TOTAL_CPU_TIME_POSTGRESQL_GAUGE[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  { "title": "TOP 20 Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 }, "repeat": "DS_PROMETHEUS" },
  {
   "title": "TOP 20 Most executed SQL with application trace",
   "type": "table",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "MOSTEXECUTE_EXECCOUNT_POSTGRESQL_GAUGE",
     "legendFormat": "{{label_name}} = exec count"
    },
    {
     "expr": "irate(MOSTEXECUTE_PERCALLMS_POSTGRESQL_GAUGE[15s])",
     "legendFormat": "{{label_name}}= per calls"
    },
    {
     "expr": "irate(MOSTEXECUTE_TEMPBLKSREAD_POSTGRESQL_GAUGE[15s])",
     "legendFormat": "{{label_name}} = TempBLK_read"
    },
    {
     "expr": "irate(MEANTIME_POSTGRESQL_GAUGE[15s])",
     "legendFormat": "{{label_name}} = Mean time"
    },
    {
     "expr": "irate(MOSTEXECUTE_ROWS_POSTGRESQL_GAUGE[15s])",
     "legendFormat": "{{label_name}} = Rows"
    },
    {
     "expr": "irate(MOSTEXECUTE_HITPERCENT_POSTGRESQL_GAUGE[15s])",
     "legendFormat": "{{label_name}} = Hit percent"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{instance=\"$instance\"}[5m])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "TOP 20 Long running  SQLs with application trace",
   "type": "table",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "WORSTEXECUTE_EXECCOUNT_POSTGRESQL_GAUGE",
     "legendFormat": "{{label_name}} = exec count"
    },
    {
     "expr": "irate(WORSTEXECUTE_ROWSPER_POSTGRESQL_GAUGE[15s])",
     "legendFormat": "{{label_name}}= per calls"
    },
    {
     "expr": "irate(MOSTEXECUTE_ROWS_POSTGRESQL_GAUGE[15s])",
     "legendFormat": "{{label_name}} = Rows"
    },
    {
     "expr": "irate(MOSTEXECUTE_HITPERCENT_POSTGRESQL_GAUGE[15s])",
     "legendFormat": "{{label_name}} = Hit percent"
    },
    {
     "expr": "irate(WORSTEXECUTE_MEANTIME_POSTGRESQL_GAUGE[15s])",
     "legendFormat": "{{label_name}} = mean time"
    }
   ]
  },
  { "title": "TABLE info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Table info used in previous run",
   "type": "table",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(TABLEANALYSISDATA_EXECCOUNT_POSTGRESQL_GAUGE[15s])",
     "legendFormat": "{{label_name}} = exec count"
    },
    {
     "expr": "irate(TABLEANALYSISDATA_PERCALLMS_POSTGRESQL_GAUGE[15s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{instance=\"$instance\"}[5m])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{instance=\"$instance\"}[5m])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  }
 ]
}