{
 "title": "PostgreSQL Database",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "appIpAddress", "label": "appIpAddress", "query": { "query": "" } },
   {
    "name": "idNum",
    "label": "Run id",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,idNum)"
    }
   },
   {
    "name": "databaseName",
    "label": "Application database",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,databaseName)"
    }
   },
   {
    "name": "usecase",
    "label": "use case",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,usecase)"
    }
   },
   {
    "name": "database",
    "label": "database",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,database)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{release=\"$release\", instance=\"$instance\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DBINSTANCE_DATABASE_SIZE{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"})"
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DBINSTANCE_TUP_UPDATED{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"})"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DBINSTANCE_TUP_INSERTED{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"})"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DBINSTANCE_TUP_UPDATED{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"})"
    }
   ]
  },
  {
   "title": "Connections in use",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DBINSTANCE_ACTIVE_CONEECTIONS{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"})",
     "legendFormat": "{{label_name}} = Connections in use"
    }
   ]
  },
  {
   "title": "Average CPU process Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_virtual_memory_max_bytes[5m]))",
     "legendFormat": "Virtual Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes[5m]))",
     "legendFormat": "Resident Mem"
    }
   ]
  },
  {
   "title": "Average CPU process Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total[5m]))",
     "legendFormat": "CPU process"
    },
    {
     "expr": "avg(rate(process_virtual_memory_max_bytes[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes[5m]))",
     "legendFormat": "Resident Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "Open FD" }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_EFFECTIVE_CACHE_SIZE{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_EFFECTIVE_CACHE_SIZE{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}"
    }
   ]
  },
  {
   "title": "REPLICATION DELAY ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_REPLICATION_DELAY_IN_SECONDS{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_WORK_MEM{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_WAL_SEGMENT_SIZE{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}"
    }
   ]
  },
  {
   "title": "Num backends",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_NUMBACKENDS{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}"
    }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_SEQ_PAGE_COST{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}\r\n"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_MAX_WORKER_PROCESSES{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_MAX_PARALLEL_WORKERS{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}"
    }
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "RUN_ACT_COUNT_POSTGRESQL", "legendFormat": "Act count" }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "RUN_TOTAL_COMMITS_POSTGRESQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "RUN_TOTAL_ROLLBACKS_POSTGRESQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "RUN_TOTAL_CALLS_POSTGRESQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{datname}} commits"
    }
   ]
  },
  {
   "title": "Average Database CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "RUN_TOTAL_CPU_TIME_POSTGRESQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "SQL throughput",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "RUN_TUP_FETCHED_POSTGRESQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{datname}} = Select"
    },
    {
     "expr": "RUN_TUP_INSERTED_POSTGRESQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{label_name}}= Insert"
    },
    {
     "expr": "RUN_TUP_UPDATED_POSTGRESQL_GAUGE{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{label_name}} = Update"
    },
    {
     "expr": "RUN_TUP_DELETED_POSTGRESQL_GAUGE{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{label_name}}= delete"
    }
   ]
  },
  {
   "title": "Waiting & locking time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "RUN_LOCKING_QUERY_DURATION_POSTGRESQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{label_name}} = Locking_QUERY_duration"
    },
    {
     "expr": "RUN_LOCKING_XACT_DURATION_POSTGRESQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{label_name}} = Locking_XACT_duration"
    },
    {
     "expr": "RUN_WAITING_QUERY_DURATION_POSTGRESQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{label_name}}= Waiting _QUERY_duration"
    },
    {
     "expr": "RUN_WAITING_XACT_DURATION_POSTGRESQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"} ",
     "legendFormat": "{{label_name}} = Waiting_XACT_duration"
    }
   ]
  },
  {
   "title": "Session info",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "WHOISACTIVE_QUERY_TIME", "legendFormat": "Query execution time" }
   ]
  },
  {
   "title": "Return data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "RUN_TUP_RETURNED_POSTGRESQL_GAUGE != 0",
     "legendFormat": "{{label_name}} = Return data"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 14, "w": 11, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "RUN_CONFLICTS_POSTGRESQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"} ",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "RUN_DEADLOCKS_POSTGRESQL{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Temp data (Bytes)",
   "type": "timeseries",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "DBINSTANCE_TEMP_BYTES{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{label_name}} = Temp_bytes"
    },
    {
     "expr": "DBINSTANCE_TEMP_FILES{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}",
     "legendFormat": "{{label_name}} = Temp files"
    }
   ]
  },
  { "title": "TOP 20 Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 }, "repeat": "DS_PROMETHEUS" },
  {
   "title": "TOP 20 Most executed SQL with application trace",
   "type": "table",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "MOSTEXECUTE_EXECCOUNT_POSTGRESQL{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} = exec count"
    },
    {
     "expr": "MOSTEXECUTE_PERCALLMS_POSTGRESQL{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}}= per calls"
    },
    {
     "expr": "MOSTEXECUTE_TEMPBLKSREAD_POSTGRESQL{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} = TempBLK_read"
    },
    {
     "expr": "MEANTIME_POSTGRESQL_GAUGE{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} = Mean time"
    },
    {
     "expr": "MOSTEXECUTE_ROWS_POSTGRESQL{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} = Rows"
    },
    {
     "expr": "MOSTEXECUTE_HITPERCENT_POSTGRESQLE{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} = Hit percent"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{instance=\"$instance\"}[5m])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "TOP 20 Long running  SQLs with application trace",
   "type": "table",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "WORSTEXECUTE_EXECCOUNT_POSTGRESQL{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} = exec count"
    },
    {
     "expr": "WORSTEXECUTE_ROWSPER_POSTGRESQL{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}}= per calls"
    },
    {
     "expr": "MOSTEXECUTE_ROWS_POSTGRESQL{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} = Rows"
    },
    {
     "expr": "MOSTEXECUTE_HITPERCENT_POSTGRESQL{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} = Hit percent"
    },
    {
     "expr": "WORSTEXECUTE_MEANTIME_POSTGRESQLE{idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} = mean time"
    }
   ]
  },
  { "title": "TABLE info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Table info used in previous run",
   "type": "table",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(TABLEANALYSISDATA_EXECCOUNT_POSTGRESQL[15s])",
     "legendFormat": "{{label_name}} = exec count"
    },
    {
     "expr": "irate(TABLEANALYSISDATA_PERCALLMS_POSTGRESQL[15s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{instance=\"$instance\"}[5m])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{instance=\"$instance\"}[5m])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  }
 ]
}