{
 "title": "SAP HANA Database template 2023-03_20",
 "description": "This dashboard works with Sap hana",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "database",
    "label": "Database type",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,database)"
    }
   },
   {
    "name": "usecase",
    "label": "use case",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,usecase)"
    }
   },
   {
    "name": "idNum",
    "label": "Run id",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,idNum)"
    }
   },
   {
    "name": "databaseName",
    "label": "Aplication_database",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,databaseName)"
    }
   },
   {
    "name": "starttimestamp",
    "label": "starttimestamp",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,starttimestamp)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database size",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DBINSTANCE_DB_SIZE{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"})\r\n"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_UPDATE_COUNT{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(DBINSTANCE_INSERT_COUNT{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"})"
    }
   ]
  },
  {
   "title": "REPLACE_COUNT ",
   "type": "stat",
   "description": "REPLACE_COUNT \nM_TABLE_STATISTICS",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(DBINSTANCE_REPLACE_COUNT{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"})"
    }
   ]
  },
  {
   "title": "Connections in use",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DBINSTANCE_ACTIVE_CONNECTION_COUNT{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "Open FD" }
   ]
  },
  {
   "title": "Average CPU Usage of executions, SAP HANA",
   "type": "timeseries",
   "description": "Displays the sum of time of the plan executions.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "RUN_TOTAL_EXECUTION_CPU_TIME_SAPHANA{databaseName=\"$databaseName\", usecase=\"$usecase\", idNum=\"$idNum\"}",
     "legendFormat": "TOTAL_EXECUTION_TIME"
    },
    {
     "expr": "RUN_TOTAL_EXECUTION_FETCH_TIME_SAPHANA{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "TOTAL_EXECUTION_FETCH_TIME"
    },
    {
     "expr": "RUN_TOTAL_EXECUTION_TIME_SAPHANA{database=\"$database\", databaseName=\"$databaseName\", usecase=\"$usecase\", idNum=\"$idNum\"}",
     "legendFormat": "TOTAL_EXECUTION_TIME"
    }
   ]
  },
  {
   "title": "Average Execution Memory Usage, SAP HANA ",
   "type": "timeseries",
   "description": "Displays the total size of tracked actual memory consumption.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "RUN_TOTAL_EXECUTION_MEMORY_SIZE_SAPHANA{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "Resident Mem"
    }
   ]
  },
  {
   "title": "Connection  counts",
   "type": "graph",
   "description": "\t\nDisplays the connection status:\n\nRUNNING\nA statement is executing.\n\nIDLE\nNo statements are currently executing on this connection.\n\nQUEUING\nThe connection is currently queued. The status changes to RUNNING when it is dequeued (this depends on the system's resource consumption).\n\nEMPTY\nA historic connection that is removed after 1 hour. The removal time can be configured in indexserver.ini [session] connection_history_lifetime = 60 # minutes.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DBINSTANCE_CONNECTION_COUNT_EMPTY{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "Empty connection"
    },
    {
     "expr": "DBINSTANCE_CONNECTION_COUNT_IDLE{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "Idle connection"
    },
    {
     "expr": "DBINSTANCE_CONNECTION_COUNT_QUEUING{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "Queuimg  connection"
    },
    {
     "expr": "DBINSTANCE_CONNECTION_COUNT_RUNNING{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "Running connection"
    }
   ]
  },
  {
   "title": "Service statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sap Hana process CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DBINSTANCE_PROCESS_CPU_TIME{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total cpu",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DBINSTANCE_TOTAL_CPU{databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DBINSTANCE_TOTAL_CPU{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process  physical memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_PROCESS_PHYSICAL_MEMORY{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_TOTAL_MEMORY{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_AVAILABLE_MEMORY{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Physical memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_PHYSICAL_MEMORY{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open file count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_OPEN_FILE_COUNT{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Information about basic I/O operations ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "Total read size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_IO_TOTAL_READ_SIZE{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total write size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_IO_TOTAL_WRITE_SIZE{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total read time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_IO_TOTAL_READ_TIME{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total write time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_IO_TOTAL_WRITE_TIME{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total IO time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_IO_TOTAL_IO_TIME{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput of file I/O can generally",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_THROUGHPUT_OF_FILE_IO{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked by ms",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "SUM(WHOISACTIVE_BLOCKEDMILLISECONDS)",
     "legendFormat": "Blocked by time"
    }
   ]
  },
  {
   "title": "Session Run time ",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "SUM(WHOISACTIVE_RUNTIME_MILLISECONDS)",
     "legendFormat": "Run time ms"
    },
    {
     "expr": "SUM(WHOISACTIVE_CURSORDURATIONMILLISECONDS)",
     "legendFormat": "Cursor duration"
    }
   ]
  },
  {
   "title": "Allocated MEM",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 10, "w": 8, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "SUM(WHOISACTIVE_AVG_EXECUTION_MEMORY_SIZE)",
     "legendFormat": "Run time ms"
    }
   ]
  },
  {
   "title": "who is active",
   "type": "table",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "WHOISACTIVE_ALLOCATED_MEMORY_SIZE"
    },
    {
     "expr": "WHOISACTIVE_BLOCKEDMILLISECONDS",
     "legendFormat": "__auto"
    },
    {
     "expr": "WHOISACTIVE_RUNTIME_MILLISECONDS"
    },
    {
     "expr": "WHOISACTIVE_CURSORDURATIONMILLISECONDS"
    }
   ]
  },
  {
   "title": "Tables used",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 15, "y": 37 },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_TABLE_SIZE_SAPHANA",
     "legendFormat": "__auto"
    },
    {
     "expr": "TABLEANALYSISDATA_TOTALEXECUTIONTIME_SAPHANA",
     "legendFormat": "__auto"
    },
    {
     "expr": "TABLEANALYSISDATA_RECORD_COUNT_SAPHANA",
     "legendFormat": "__auto"
    },
    {
     "expr": "TABLEANALYSISDATA_EXECCOUNT_SAPHANA",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Execution count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "RUN_EXECUTION_COUNT_SAPHANA{database=\"$database\", databaseName=\"$databaseName\", usecase=\"$usecase\", idNum=\"$idNum\"} != 0",
     "legendFormat": "{{label_name}} Executions"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "RUN_M_TRANSACTIONS_ACTIVE_SAPHANA{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} Active"
    },
    {
     "expr": "RUN_M_TRANSACTIONS_INACTIVE_SAPHANA{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} Inactive"
    }
   ]
  },
  {
   "title": "Waiting & locking time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "RUN_TOTAL_LOCK_WAIT_COUNT_SAPHANA{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}}Locki wait count"
    }
   ]
  },
  {
   "title": "Log THROUGHPUT MB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "RUN_LOGREADTHROUGHPUTMB_SAPHANA {database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} LOG READ THROUGHPUT MB"
    },
    {
     "expr": "RUN_LOGWRITETHROUGHPUTMB{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} LOG WRITE THROUGHPUT MB"
    }
   ]
  },
  {
   "title": "Data process",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "RUN_DATA_READS_MB_SAPHANA{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"} != 0",
     "legendFormat": "{{label_name}} Reads"
    },
    {
     "expr": "RUN_DATAWRITESMB_SAPHANA {database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}!= 0",
     "legendFormat": "{{label_name}} Writes"
    }
   ]
  },
  {
   "title": "Lock wait time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "TOTAL_LOCK_WAIT_DURATION{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection details",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "RUN_AVG_CURSOR_DURATION_SAPHANA{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} Cursor duration AVG"
    },
    {
     "expr": "RUN_IDLE_TIME_MS_SAPHANA{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} Idle time"
    }
   ]
  },
  { "title": "TOP 20 SQL details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Top 20 most executed queries",
   "type": "table",
   "description": "Latest start & stop recording queries for selected usecase",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_EXECCOUNT_SAPHANA {database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"} !=0",
     "legendFormat": "__auto"
    },
    {
     "expr": "MOSTEXECUTE_TOTALEXECUTIONCPUTIME_SAPHANA {database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"} !=0",
     "legendFormat": "__auto"
    },
    {
     "expr": "MOSTEXECUTE_TOTALEXECUTIONMEMORYSIZE_SAPHANA {database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"} !=0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOP 20 most executed queries",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "MOSTEXECUTE_EXECCOUNT_SAPHANA{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}!=0",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top 20 long running queries",
   "type": "table",
   "description": "Latest start & stop recording queries for selected use case",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "WORSTEXECUTE_TOTALEXECUTIONTIME_SAPHANA{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}!=0\r\n\r\n\r\n\r\n\r\n\r\n\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "WORSTEXECUTE_TOTALEXECUTIONTIME_SAPHANA{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}!=0",
     "legendFormat": "__auto"
    },
    {
     "expr": "WORSTEXECUTE_TOTALLOCKWAITDURATION_SAPHANA{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "MOSTEXECUTE_EXECCOUNT_SAPHANA{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"} !=0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOP 20 long running queries",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "WORSTEXECUTE_TOTALEXECUTIONTIME_SAPHANA{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}\r\n\r\n\r\n\r\n\r\n\r\n",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "who is active",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "WHOISACTIVE_ALLOCATED_MEMORY_SIZE"
    },
    {
     "expr": "WHOISACTIVE_BLOCKEDMILLISECONDS",
     "legendFormat": "__auto"
    },
    {
     "expr": "WHOISACTIVE_RUNTIME_MILLISECONDS"
    },
    {
     "expr": "WHOISACTIVE_CURSORDURATIONMILLISECONDS"
    }
   ]
  }
 ]
}