{
 "title": "SQL SERVER Database template 2023-02-28",
 "description": "This dashboard works with Sap hana",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "database",
    "label": "Database type",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,database)"
    }
   },
   {
    "name": "usecase",
    "label": "use case",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,usecase)"
    }
   },
   {
    "name": "idNum",
    "label": "Run id",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,idNum)"
    }
   },
   {
    "name": "databaseName",
    "label": "Aplication_database",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,databaseName)"
    }
   },
   {
    "name": "starttimestamp",
    "label": "starttimestamp",
    "query": {
     "query": "label_values(DBINSTANCE_ID_NUM,starttimestamp)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database size",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_SIZEMB{database=\"$database\",databaseName=\"$databaseName\",idNum=\"$idNum\",usecase=\"$usecase\"}"
    }
   ]
  },
  {
   "title": "CPU count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_CPU_COUNT{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffer hit ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_BUFFERCACHEHITRATIO{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}"
    }
   ]
  },
  {
   "title": "SQL Attention rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_SQL_ATTENTION_RATE{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}"
    }
   ]
  },
  {
   "title": "Connections in use",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_USER_CONNECTIONS{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "Open FD" }
   ]
  },
  {
   "title": "Complications",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "RUN_SQLCOMPILATIONSSEC_MSSQL{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} SQL COMPILATIONS SEC"
    },
    {
     "expr": "RUN_SQLRE_COMPILATIONS_SEC_MSSQL{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} SQL RE COMPILATIONS SEC"
    }
   ]
  },
  {
   "title": "Number of executions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "RUN_NUM_EXECUTIONS_MSSQL{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "Num executions"
    }
   ]
  },
  {
   "title": " Worker time usage of executions",
   "type": "timeseries",
   "description": "Displays the sum of time of the plan executions.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "RUN_TOTAL_WORKER_TIME_MSSQL{database=\"$database\", databaseName=\"$databaseName\", usecase=\"$usecase\", idNum=\"$idNum\"}",
     "legendFormat": "Worker time"
    },
    {
     "expr": "RUN_TOTAL_ELAPSED_TIME{database=\"$database\", databaseName=\"$databaseName\", usecase=\"$usecase\", idNum=\"$idNum\"}",
     "legendFormat": "Elapsed time"
    }
   ]
  },
  { "title": "Session live metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "who is active",
   "type": "table",
   "gridPos": { "h": 18, "w": 14, "x": 0, "y": 21 },
   "targets": [
    { "expr": "WHOISACTIVE_TOTALCPU_MS", "legendFormat": "__auto" },
    { "expr": "WHOISACTIVE_MEMUSAGE_KB", "legendFormat": "__auto" },
    { "expr": "WHOISACTIVE_TOTALPHYIO_MB", "legendFormat": "__auto" },
    { "expr": "WHOISACTIVE_WAITTIME_MS", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Session  MEM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    { "expr": "avg(WHOISACTIVE_MEMUSAGE_KB)", "legendFormat": "Mem usage" }
   ]
  },
  {
   "title": "Session  CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "avg(WHOISACTIVE_TOTALCPU_MS)", "legendFormat": "Total CPU" }
   ]
  },
  {
   "title": "Session  Waiting time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "avg(WHOISACTIVE_WAITTIME_MS)", "legendFormat": "Waiting time" }
   ]
  },
  {
   "title": "Reads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "RUN_TOTAL_PHYSICAL_READS_MSSQL{database=\"$database\", databaseName=\"$databaseName\", usecase=\"$usecase\", idNum=\"$idNum\"} != 0",
     "legendFormat": "{{label_name}} PHYSICAL_READS"
    },
    {
     "expr": "RUN_TOTAL_LOGICAL_READS_MSSQL{database=\"$database\", databaseName=\"$databaseName\", usecase=\"$usecase\", idNum=\"$idNum\"} != 0",
     "legendFormat": "{{label_name}} LOGICAL_READS"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "description": "\t\nDisplays the connection status:\n\nRUNNING\nA statement is executing.\n\nIDLE\nNo statements are currently executing on this connection.\n\nQUEUING\nThe connection is currently queued. The status changes to RUNNING when it is dequeued (this depends on the system's resource consumption).\n\nEMPTY\nA historic connection that is removed after 1 hour. The removal time can be configured in indexserver.ini [session] connection_history_lifetime = 60 # minutes.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "RUN_TRANSACTIONS_ACTIVE_MSSQL{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "RUN_TRANSACTIONDELAY_MSSQL{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "Delay"
    },
    {
     "expr": "RUN_TRANSACTIONS_SEC_MSSQL{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "Transactions sec"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "RUN_ERRORS_SEC_MSSQL{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}}  errors"
    }
   ]
  },
  {
   "title": "OS SYS Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OS_SYS_VIRTUAL_MEMORY",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_OS_SYS_VIRTUAL_MEMORY_KB{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS_SYS_COMMITTED",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_OS_SYS_COMMITTED_KB{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS_SYS_COMMITTED_TARGET",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_OS_SYS_COMMITTED_TARGET_KB{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_OS_SYS_PHYSICAL_MEMORY_KB{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SYS_PROCESS_USER_TIME",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_OS_SYS_PROCESS_USER_TIME_MS{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL IO ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_TOTALIOMB{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PROCESS KERNEL TIME",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_PROCESS_KERNEL_TIME_MS{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Information about basic I/O operations ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }
  },
  {
   "title": "Total number of reads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_TOTALNUMOFWRITES{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_TOTALNUMOFBYTESREAD{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of write s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_TOTALNUMOFWRITES{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total write time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_TOTALNUMOFBYTESREAD{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total IO time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_BULK_COPY_THROUGHPUT_SEC{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FAILED_AUTO_PARAMS_SEC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_FAILED_AUTO_PARAMS_SEC{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FAILED_AUTO_PARAMS_SEC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "RUN_PARTITIONS__MSSQL{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "RUN_TOTAL_LOGICAL_WRITES_MSSQL{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}}Logical writes"
    }
   ]
  },
  {
   "title": "Curson",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "RUN_NUMBER_OF_ACTIVE_CURSOR_PLANS_MSSQL{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} Active plans"
    },
    {
     "expr": "RUN_IDLE_TIME_MS_SAPHANA{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} Idle time"
    }
   ]
  },
  {
   "title": "Data read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "RUN_READBYTESSEC_MSSQL{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"} != 0",
     "legendFormat": "{{label_name}} Reads"
    }
   ]
  },
  {
   "title": "Log THROUGHPUT MB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "RUN_LOGFILESSIZEKB_MSSQL {database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} LOG READ THROUGHPUT MB"
    },
    {
     "expr": "RUN_LOGWRITETHROUGHPUTMB{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "{{label_name}} LOG WRITE THROUGHPUT MB"
    }
   ]
  },
  { "title": "TOP 20 SQL details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Top 20 most executed queries",
   "type": "table",
   "description": "Latest start & stop recording queries for selected usecase",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_EXECCOUNT_MSSQL {database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"} !=0",
     "legendFormat": "__auto"
    },
    {
     "expr": "MOSTEXECUTE_TOTAL_ELAPSED_TIME_MSSQL {database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"} !=0",
     "legendFormat": "__auto"
    },
    {
     "expr": "MOSTEXECUTE_LAST_LOGICAL_READS_MSSQL {database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"} !=0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOP 20 most executed queries",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "MOSTEXECUTE_EXECCOUNT_MSSQL{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}!=0",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Top 20 long running queries",
   "type": "table",
   "description": "Latest start & stop recording queries for selected use case",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "WORSTEXECUTE_TOTAL_ELAPSED_TIME_MSSQL{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "WORSTEXECUTE_TOTAL_ROWS_MSSQL{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "WORSTEXECUTE_TOTAL_LOGICAL_READS_MSSQL{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "WORSTEXECUTE_TOTAL_PHYSICAL_READS_MSSQL{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOP 20 slow runnig queries",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "WORSTEXECUTE_TOTAL_ELAPSED_TIME_MSSQL{database=\"$database\",databaseName=\"$databaseName\",usecase=\"$usecase\",idNum=\"$idNum\"}!=0",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  { "title": "WHO IS ACTIVE, session details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "who is active",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 106 },
   "targets": [
    { "expr": "WHOISACTIVE_TOTALCPU_MS", "legendFormat": "__auto" },
    { "expr": "WHOISACTIVE_MEMUSAGE_KB", "legendFormat": "__auto" },
    { "expr": "WHOISACTIVE_TOTALPHYIO_MB", "legendFormat": "__auto" },
    { "expr": "WHOISACTIVE_WAITTIME_MS", "legendFormat": "__auto" }
   ]
  }
 ]
}